### ISSUE TITLE
exe打不开闪退

### ISSUE THREAD

**Issue by mengqidiluff** [staparx/go_showstart#1]
大佬，exe下载下来，打不开，直接闪退，是不是win11系统不兼容啊

**Comment by staparx** [comment]
运行后看看当前目录下是否有log文件生成，可以发一下里面的错误日志看看。

**Comment by staparx** [comment]
> 大佬，exe下载下来，打不开，直接闪退，是不是win11系统不兼容啊

没考虑到可执行文件读取配置文件的路径问题，新版本中已解决该问题。
