### ISSUE TITLE
当票价有打折的情况，比如标注的原价468，现在398，会查询不到价格

### ISSUE THREAD

**Issue by YUHsss** [staparx/go_showstart#11]
![IMG_5330](https://github.com/user-attachments/assets/c9f2d3b6-8089-43a5-858e-aace43e96526)

**Comment by cr4n5** [comment]
你把演唱会id发一下，或者名字啥的，我看看

**Comment by YUHsss** [comment]
246946

**Comment by cr4n5** [comment]
我看了下这个场次，你的session name应该得这个格式（中间有三个空格），属于是秀动官方有点（，
session: "2024-11-22   20:00"
![image](https://github.com/user-attachments/assets/473fbae9-8364-4a1b-b263-a1fe29759257)

**Comment by YUHsss** [comment]
![IMG_5331](https://github.com/user-attachments/assets/c797718a-1032-4d8a-8955-c2eff68600a2)
大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了

**Comment by YUHsss** [comment]
> > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> 
> 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧

![image](https://github.com/user-attachments/assets/4f7bc148-eb02-4772-ab82-9f50f224a401)
大佬一开始就出现这个什么意思

**Comment by cr4n5** [comment]
> > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> > 
> > 
> > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> 
> ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思

我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”

**Comment by YUHsss** [comment]
> > > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> > > 
> > > 
> > > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思
> 
> 我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”

那这个会影响抢钱吗，或者可以怎么规避呢？
还有一个问题想请教一下，就是如果按实际抢票时间设定，程序会提前两秒，是不是可能会出现在实际时间前面就扑空了

**Comment by cr4n5** [comment]
> > > > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> > > > 
> > > > 
> > > > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思
> > 
> > 
> > 我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”
> 
> 那这个会影响抢票吗，或者可以怎么规避呢？ 还有一个问题想请教一下，就是如果按实际抢票时间设定，程序会提前两秒，是不是可能会出现在实际时间前面就扑空了

你前面这个截图情况用的是作者的，还是我后面修改的啊？这个“参数不可重复提交”我也不确定会不会影响抢票，这个得看秀d后端处理逻辑。对于程序提前两秒开始，作者在 https://github.com/staparx/go_showstart/issues/5 有说，但是我也不确定，我自行测试的时候，也是极其容易扑空的，导致未开票，然后需卡着3s左右的“下单速度过快”,然后后续的抢票就没库存了，这个问题得问问作者。

**Comment by cr4n5** [comment]
> > > > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> > > > 
> > > > 
> > > > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思
> > 
> > 
> > 我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”
> 
> 那这个会影响抢票吗，或者可以怎么规避呢？ 还有一个问题想请教一下，就是如果按实际抢票时间设定，程序会提前两秒，是不是可能会出现在实际时间前面就扑空了

我想的是，取消提前的两秒，准时启动是最好的。对于热门的票，基本上就取决于你第一次的抢票请求了，没抢到就是直接没库存，只能等回流。

**Comment by YUHsss** [comment]
> > > > > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> > > > > 
> > > > > 
> > > > > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思
> > > 
> > > 
> > > 我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”
> > 
> > 
> > 那这个会影响抢票吗，或者可以怎么规避呢？ 还有一个问题想请教一下，就是如果按实际抢票时间设定，程序会提前两秒，是不是可能会出现在实际时间前面就扑空了
> 
> 我想的是，取消提前的两秒，准时启动是最好的。对于热门的票，基本上就取决于你第一次的抢票请求了，没抢到就是直接没库存，只能等回流。

但是我看你目前提供的版本是不是也还是提前2秒，我看启动info 里面显示

**Comment by cr4n5** [comment]
> > > > > > > ![IMG_5331](https://private-user-images.githubusercontent.com/108503577/384448259-c797718a-1032-4d8a-8955-c2eff68600a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQzMDEsIm5iZiI6MTczMTA4NDAwMSwicGF0aCI6Ii8xMDg1MDM1NzcvMzg0NDQ4MjU5LWM3OTc3MThhLTEwMzItNGQ4YS04OTU1LWMyZWZmNjg2MDBhMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTY0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTNiMWI0MDQ0Mzc4Njc5ZjkyMDRlMjJkOGVlZWNlZDY4NGJkMzQxNjMyY2NkMGMxNDZhZjliMDliYzA5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._W-3_57H0Nd16Mr5sebHJzXEWrF0R0Su850BaCHOqc0) 大佬，我用的作者开放的集成软件，我试了试其他的就可以正常运行，当这个id就不行了
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 得是这样session: "2024-11-22 20:00" 在2024-11-22和20:00之间有三个空格 这样就行了，周五不用加 我也不知道为什么官方这样处理的，后续我修改一下代码里的匹配规则吧
> 
> > > > > 
> 
> > > > > 
> 
> > > > > ![image](https://private-user-images.githubusercontent.com/108503577/388926448-4f7bc148-eb02-4772-ab82-9f50f224a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzk4NDgsIm5iZiI6MTczMjI3OTU0OCwicGF0aCI6Ii8xMDg1MDM1NzcvMzg4OTI2NDQ4LTRmN2JjMTQ4LWViMDItNDc3Mi1hYjgyLTlmNTBmMjI0YTQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjQ1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDAwZWU4M2JkNGM1ODNlNDhiOTJlODEzZWZkZWQwOTlmYjg1ZWY3YjFkZTUwNDM2OTVlZmFlM2QwODBmYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oTD4TUufjbOQViBIU7Fv_1qGKymrKLdk34P8UbrspAw) 大佬一开始就出现这个什么意思
> 
> > > > 
> 
> > > > 
> 
> > > > 我取消了开始抢票的时间的随机延迟，三个会话是同时开始发送抢票请求的，所以会导致“参数不可重复提交”
> 
> > > 
> 
> > > 
> 
> > > 那这个会影响抢票吗，或者可以怎么规避呢？ 还有一个问题想请教一下，就是如果按实际抢票时间设定，程序会提前两秒，是不是可能会出现在实际时间前面就扑空了
> 
> > 
> 
> > 我想的是，取消提前的两秒，准时启动是最好的。对于热门的票，基本上就取决于你第一次的抢票请求了，没抢到就是直接没库存，只能等回流。
> 
> 
> 
> 但是我看你目前提供的版本是不是也还是提前2秒，我看启动info 里面显示

你可以定的start time多2s呀
