### ISSUE TITLE
请问是否可以加入钉钉的机器人提醒功能？抢到票的话直接提醒

### ISSUE THREAD

**Issue by 1210410392** [staparx/go_showstart#14]
之前一开票没抢到，它就在抢回流，抢了很久。结果后来发现回流抢到了，但我错过了支付时间！能否考虑一下加入提醒功能，微信或者钉钉都可以

**Comment by cr4n5** [comment]
https://github.com/staparx/go_showstart/pull/10 我添加了个邮箱提醒的功能

**Comment by 1210410392** [comment]
> #10 我添加了个邮箱提醒的功能

是要自己编译吗？我不知道怎么弄诶，而且我发现会出现 提示[0]下单成功！核心订单Key：
[0]核心订单Key为空，但实际并没有订单的情况，

**Comment by 1210410392** [comment]
> #10 我添加了个邮箱提醒的功能

好吧 我才发现你不是原作者

**Comment by cr4n5** [comment]
https://github.com/cr4n5/go_showstart 我在fork仓库里编译好了

> > #10 我添加了个邮箱提醒的功能
> 
> 是要自己编译吗？我不知道怎么弄诶，而且我发现会出现 提示[0]下单成功！核心订单Key： [0]核心订单Key为空，但实际并没有订单的情况，

https://github.com/cr4n5/go_showstart 我刚刚在fork仓库里编译好了，核心订单为空的情况我也修复了

**Comment by cr4n5** [comment]
> > #10 我添加了个邮箱提醒的功能
> 
> 是要自己编译吗？我不知道怎么弄诶，而且我发现会出现 提示[0]下单成功！核心订单Key： [0]核心订单Key为空，但实际并没有订单的情况，

https://github.com/cr4n5/go_showstart 我刚刚在fork仓库里编译好了，核心订单为空的情况我也修复了

**Comment by 1210410392** [comment]
> > > #10 我添加了个邮箱提醒的功能
> > 
> > 
> > 是要自己编译吗？我不知道怎么弄诶，而且我发现会出现 提示[0]下单成功！核心订单Key： [0]核心订单Key为空，但实际并没有订单的情况，
> 
> https://github.com/cr4n5/go_showstart 我刚刚在fork仓库里编译好了，核心订单为空的情况我也修复了

太感谢了！！！！！！

**Comment by staparx** [comment]
已经邮箱提醒功能合并，最新版本可见。
