### ISSUE TITLE
提前2s启动问题

### ISSUE THREAD

**Issue by cr4n5** [staparx/go_showstart#15]
如 https://github.com/staparx/go_showstart/issues/5 想问一下，提前2s启动的的预启动体现在哪里，提前启动很容易导致“还未开票”，然后会有3s左右的“下单速度过快”，导致抢不到票。我看代码部分还是在预定时间发order请求

**Comment by staparx** [comment]
已删除，具体位置可见commit
https://github.com/staparx/go_showstart/commit/7821cf6cf3488e2c07720acf5521bd8a4f6c1ef6
