### ISSUE TITLE
workflow编译出的exe初始化时区失败

### ISSUE THREAD

**Issue by BakaDream** [staparx/go_showstart#2]
我从release下载的exe运行提示初始化时区失败{"error": "unknown time zone Asia/Shanghai"}
然后我把代码clone下载在我本地编译后运行就没事。
是不是workflow使用的镜像的问题？

**Comment by staparx** [comment]
> 我从release下载的exe运行提示初始化时区失败{"error": "unknown time zone Asia/Shanghai"} 然后我把代码clone下载在我本地编译后运行就没事。 是不是workflow使用的镜像的问题？

麻烦提供一下你下载的版本号，最新一版应该已经处理了时区问题了。

**Comment by BakaDream** [comment]
[Release 20240819025744-6472bf619373e048b5fd32ca440cf837d6094f0b-6472bf6](https://github.com/staparx/go_showstart/releases/tag/20240819025744-6472bf619373e048b5fd32ca440cf837d6094f0b-6472bf6) 这个 windows amd 64

**Comment by Benson-Lim-7** [comment]
+1

**Comment by staparx** [comment]
最新一版已经更改了时区问题，当location库读取失败时，会采用FixedZone的方式手动定义时区。
