### ISSUE TITLE
每次开抢，总是会先提示{"error": "参数不可重复提交."}

### ISSUE THREAD

**Issue by 1210410392** [staparx/go_showstart#21]
{"error": "参数不可重复提交."}
设置的是
3
200
500
要怎么避免这样？

**Comment by cr4n5** [comment]
> {"error": "参数不可重复提交."}
> 
> 设置的是
> 
> 3
> 
> 200
> 
> 500
> 
> 要怎么避免这样？

在我fork的仓库已经更改了，你可以试试

**Comment by 1210410392** [comment]
我用的就是你的版本，加了毫秒级的版本

**Comment by 1210410392** [comment]
> > {"error": "参数不可重复提交."}
> > 设置的是
> > 3
> > 200
> > 500
> > 要怎么避免这样？
> 
> 在我fork的仓库已经更改了，你可以试试
我用的就是你的版本，加了毫秒级的版本，所以觉得奇怪 我记得之前有人提过这个问题

**Comment by cr4n5** [comment]
> > > {"error": "参数不可重复提交."}
> 
> > > 设置的是
> 
> > > 3
> 
> > > 200
> 
> > > 500
> 
> > > 要怎么避免这样？
> 
> > 
> 
> > 在我fork的仓库已经更改了，你可以试试
> 
> 我用的就是你的版本，加了毫秒级的版本，所以觉得奇怪 我记得之前有人提过这个问题
> 
> 

防止参数重复是提高时间精度的后面一个版本，我不确定你是不是，按理来说现在很少会在开票时出现这个“参数重复”，要不你提供一下你的log文件？

**Comment by 1210410392** [comment]
> > > > {"error": "参数不可重复提交."}
> > 
> > 
> > > > 设置的是
> > 
> > 
> > > > 3
> > 
> > 
> > > > 200
> > 
> > 
> > > > 500
> > 
> > 
> > > > 要怎么避免这样？
> > 
> > 
> > > 
> > 
> > 
> > > 在我fork的仓库已经更改了，你可以试试
> > 
> > 
> > 我用的就是你的版本，加了毫秒级的版本，所以觉得奇怪 我记得之前有人提过这个问题
> 
> 防止参数重复是提高时间精度的后面一个版本，我不确定你是不是，按理来说现在很少会在开票时出现这个“参数重复”，要不你提供一下你的log文件？

确实我更新了今天最新版以后就好了，非常感谢！还有一个小问题，请问最大并发数和请求间隔有没有推荐的设置？因为每次都会看到一大片的"下单速度过快,稍后重试"
