### ISSUE TITLE
匹配票档失败! 在场次中未找寻到对应票价的信息

### ISSUE THREAD

**Issue by debby97cheer** [staparx/go_showstart#8]
<img width="867" alt="微信图片_20241018001117" src="https://github.com/user-attachments/assets/c326cb81-99f2-4694-9008-c3dfa47f65ee">
奇怪 时间价格没填错 不知道为啥会这样

**Comment by debby97cheer** [comment]
ticket:
  activity_id: 244948
  start_time: "2024-10-18 12:00:00"
  list:
    - session: "2024-12-14 周六 20:00"
      price: "220"

**Comment by cr4n5** [comment]
> ticket: activity_id: 244948 start_time: "2024-10-18 12:00:00" list: - session: "2024-12-14 周六 20:00" price: "220"

应该是填“12月14日上海站”

**Comment by azJoe123** [comment]
> > ticket: activity_id: 244948 start_time: "2024-10-18 12:00:00" list: - session: "2024-12-14 周六 20:00" price: "220"
> 
> 应该是填“12月14日上海站”

我也有这个问题，顺利解决抢到了感谢大佬。我“- session:”这一项它填显示的选项内容就可以了
