### ISSUE TITLE
为什么获取不到核心订单key为空呢

### ISSUE THREAD

**Issue by jingming111** [staparx/go_showstart#9]
![屏幕截图 2024-10-18 212833](https://github.com/user-attachments/assets/3a300cb8-3b07-485a-9e97-b3c007a5b87c)

**Comment by cloud666666666** [comment]
我也是

**Comment by cr4n5** [comment]
见 https://github.com/staparx/go_showstart/pull/10

**Comment by staparx** [comment]
已合并，最新版本可见。
